# Generated by Django 5.1.7 on 2025-03-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='company_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
