# Generated by Django 5.1.7 on 2025-03-31 14:54

from django.db import migrations, models

def copy_existing_data(apps, schema_editor):
    Contacts = apps.get_model("common", "Contacts")
    for contact in Contacts.objects.all():
        contact.company_name_ru = contact.company_name

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_contacts_company_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.RunPython(copy_existing_data)

    ]
