# Generated by Django 5.1.7 on 2025-03-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Кыргызстан г.Бишкек , ул.Киевская 168')),
                ('time_work', models.TimeField(default='Работаем с 09:00 до 18:00', max_length=255, verbose_name='Время работы')),
                ('number_phone', models.CharField(max_length=255, verbose_name='Тел: +(996) 709234564; 505764323')),
                ('gmai', models.CharField(max_length=255, verbose_name='Email: info@softech.com')),
            ],
        ),
    ]
