# Generated by Django 5.1.7 on 2025-03-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='gmai',
            field=models.CharField(max_length=255, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Местоположения'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='number_phone',
            field=models.CharField(max_length=255, verbose_name='Тел:'),
        ),
    ]
