# Generated by Django 5.1.7 on 2025-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(max_length=100, null=True, verbose_name='ссылка'),
        ),
    ]
