# Generated by Django 5.1.7 on 2025-04-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_remove_item_sub_category_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
    ]
